// Resolves how this app instance should identify a "room" for both local
// storage isolation and (optionally) live collaboration sync. Two sources,
// checked in order:
//
//   1. Widget mode — Element substitutes matrix_room_id into the URL when
//      this app is embedded via /addwidget. Everyone viewing the widget in
//      the same Matrix room shares the same room id automatically.
//   2. Standalone collab session — visiting /collab/<id> (generated by the
//      "Start collaboration" button) puts unrelated standalone visitors
//      into a shared session without any Matrix room involved.
//
// A plain visit to the site (neither of the above) leaves everything here
// empty/false, which is exactly the original standalone behaviour: fully
// local, no network sync, unnamespaced storage.
const params = new URLSearchParams(window.location.search)

const rawRoomId = params.get('matrix_room_id') || ''
export const isWidget = !!params.get('widgetId')

const collabMatch = window.location.pathname.match(/^\/collab\/([a-zA-Z0-9_-]+)/)
export const collabSessionId = collabMatch ? collabMatch[1] : ''
export const isCollabSession = !!collabSessionId

// The id used for both storage namespacing and the sync room key.
const rawSyncId = rawRoomId || collabSessionId
export const syncRoomId = rawSyncId

// Storage namespace derived the same way, sanitised for use as an
// IndexedDB database name / localStorage key fragment.
export const roomNamespace = rawSyncId ? rawSyncId.replace(/[^a-zA-Z0-9_-]/g, '_') : ''

export const widgetId    = params.get('widgetId') || ''
export const widgetTheme = params.get('theme') || ''
export const matrixUserId = params.get('matrix_user_id') || ''

// True whenever there's someone to sync with over the network — either a
// Matrix room (widget) or a standalone collab session.
export const isSyncActive = !!syncRoomId

// Used by the "Start collaboration" button to mint a new standalone session id.
export function generateCollabSessionId() {
  return Math.random().toString(36).slice(2, 10) + Date.now().toString(36).slice(-4)
}
